version: '3.9'

services:
  # MongoDB services
  mongo_db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://mongo_db:27017/IE_HW2_DB
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}

